### ISSUE TITLE
Document replace method

### ISSUE THREAD

**Issue by keremcankaya0** [crassaert/php-azure-documentdb#4]
Document replace requires _rid in the url path.
I've fixed adding a basic if method is put add _rid to end condition in Document.create method.

Thanks for sharing man.

**Comment by crassaert** [comment]
Thanks ! Could you do a pull request to merge changes into this repo ?

**Comment by un-matthewdavis** [comment]
Interested in this code as well. I added the document `_rid` to the end of the URL, but subsequently get another error:

> The input authorization token can't serve the request. Please check that the expected payload is built as per the protocol, and check the key being used.

**Comment by keremcankaya0** [comment]
@crassaert I've reformatted the library according to our teams requirements but i'll give you a hand as soon as I'm done with that version. Thanks again, life saving library!

@un-matthewdavis Problem is with your payload, although you're replacing a document you need to add the collection resource_id in your signature.
